services:
  api:
    build: .
    command: npm run dev # nodemon live reload
    environment:
      DATABASE_URL: ${DATABASE_URL}
      NODE_ENV: development
      PORT: 8080
    volumes:
      - ./:/app # Sync source code for live reload
      - /app/node_modules # Prevent overwriting node_modules
    ports:
      - "8080:8080"
